state_sync_rpc = [
    "http://161.35.131.10:26657",
    "http://161.35.131.10:26657",
]
tendermint_flags = ["--p2p.seeds", """
        8b5e053e378ee12ece425f63324054d7ed7ef73f@161.35.131.10:26656,\
    """]
btc_relayer = ["https://relayer.stbtc-testnet.mappum.io:8443"]

genesis = """
{
  "app_hash": "",
  "chain_id": "stbtc-testnet-0",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
      "max_age_duration": "172800000000000",
      "max_age_num_blocks": "100000",
      "max_bytes": "1048576"
    },
    "validator": {
      "pub_key_types": [
        "ed25519"
      ]
    },
    "version": {}
  },
  "genesis_time": "2024-04-09T00:10:43.327809373Z",
  "initial_height": "0",
  "validators": [
    {
      "address": "733FD15403CC8EFED0CE886F0F21366164DAF3A2",
      "name": "",
      "power": "10",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "ngphveLsJZ2GHtr2D42SA4zyapDWXA/ZomXr6ECMmEk="
      }
    }
  ]
}
"""
